Add friendly prompt for default value
nvdaaddons/addonWizzard pull request #3
Opened 2018-08-17 09:55 UTC by larry801

When I first used this wizard. The prompt for the default value confused me a lot. I wanted to delete the default value and enter my own. I added more text to the prompt to avoid confusion.
Please see issue #2 for detail.

2018-09-12 00:59 UTC, derekriemer requested changes
Thanks for the fix.  Please address this review comment and I'll make sure to submit this.

2018-09-12 00:59 UTC, derekriemer commented on NVDAAddonTemplate/__init__.py
> +		default_prompt = "The default value is:(" + default + ")Please enter your choice"
Would something like this be a better choice?

Default: {default}
Please enter a value, or press enter to accept the default.

Also, please use a format string like this. it's easier if we decide to translate, and cleaner for changing later.

`		default_prompt = "The default value is: {default} Please enter your choice".format(default)`

2018-09-12 01:41 UTC, larry801 commented
I have made requested changes and tested locally.

2018-09-16 05:38 UTC, derekriemer approved these changes

2018-09-16 05:38 UTC, derekriemer commented
Thanks for doing this.

2018-09-16 07:03 UTC, merged